//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.asae.com.mx", ConfigurationName="ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap")]
    public interface CorreoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento host del espacio de nombres http://www.asae.com.mx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.asae.com.mx/CorreoMetPrivado", ReplyAction="*")]
        CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoResponse CorreoMetPrivado(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.asae.com.mx/CorreoMetPrivado", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoResponse> CorreoMetPrivadoAsync(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento host del espacio de nombres http://www.asae.com.mx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.asae.com.mx/CorreoAsaeTickets", ReplyAction="*")]
        CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsResponse CorreoAsaeTickets(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.asae.com.mx/CorreoAsaeTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsResponse> CorreoAsaeTicketsAsync(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento host del espacio de nombres http://www.asae.com.mx no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.asae.com.mx/CorreoAsaeCRM_AgendaEvento", ReplyAction="*")]
        CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoResponse CorreoAsaeCRM_AgendaEvento(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.asae.com.mx/CorreoAsaeCRM_AgendaEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoResponse> CorreoAsaeCRM_AgendaEventoAsync(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CorreoMetPrivadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CorreoMetPrivado", Namespace="http://www.asae.com.mx", Order=0)]
        public CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequestBody Body;
        
        public CorreoMetPrivadoRequest() {
        }
        
        public CorreoMetPrivadoRequest(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.asae.com.mx")]
    public partial class CorreoMetPrivadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int puerto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contra;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string body;
        
        public CorreoMetPrivadoRequestBody() {
        }
        
        public CorreoMetPrivadoRequestBody(string host, int puerto, string usuario, string contra, string Email, string from, string Subject, string body) {
            this.host = host;
            this.puerto = puerto;
            this.usuario = usuario;
            this.contra = contra;
            this.Email = Email;
            this.from = from;
            this.Subject = Subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CorreoMetPrivadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CorreoMetPrivadoResponse", Namespace="http://www.asae.com.mx", Order=0)]
        public CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoResponseBody Body;
        
        public CorreoMetPrivadoResponse() {
        }
        
        public CorreoMetPrivadoResponse(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.asae.com.mx")]
    public partial class CorreoMetPrivadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorreoMetPrivadoResult;
        
        public CorreoMetPrivadoResponseBody() {
        }
        
        public CorreoMetPrivadoResponseBody(string CorreoMetPrivadoResult) {
            this.CorreoMetPrivadoResult = CorreoMetPrivadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CorreoAsaeTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CorreoAsaeTickets", Namespace="http://www.asae.com.mx", Order=0)]
        public CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequestBody Body;
        
        public CorreoAsaeTicketsRequest() {
        }
        
        public CorreoAsaeTicketsRequest(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.asae.com.mx")]
    public partial class CorreoAsaeTicketsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int puerto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contra;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmailCopia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string body;
        
        public CorreoAsaeTicketsRequestBody() {
        }
        
        public CorreoAsaeTicketsRequestBody(string host, int puerto, string usuario, string contra, string Email, string EmailCopia, string from, string Subject, string body) {
            this.host = host;
            this.puerto = puerto;
            this.usuario = usuario;
            this.contra = contra;
            this.Email = Email;
            this.EmailCopia = EmailCopia;
            this.from = from;
            this.Subject = Subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CorreoAsaeTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CorreoAsaeTicketsResponse", Namespace="http://www.asae.com.mx", Order=0)]
        public CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsResponseBody Body;
        
        public CorreoAsaeTicketsResponse() {
        }
        
        public CorreoAsaeTicketsResponse(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.asae.com.mx")]
    public partial class CorreoAsaeTicketsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorreoAsaeTicketsResult;
        
        public CorreoAsaeTicketsResponseBody() {
        }
        
        public CorreoAsaeTicketsResponseBody(string CorreoAsaeTicketsResult) {
            this.CorreoAsaeTicketsResult = CorreoAsaeTicketsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CorreoAsaeCRM_AgendaEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CorreoAsaeCRM_AgendaEvento", Namespace="http://www.asae.com.mx", Order=0)]
        public CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequestBody Body;
        
        public CorreoAsaeCRM_AgendaEventoRequest() {
        }
        
        public CorreoAsaeCRM_AgendaEventoRequest(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.asae.com.mx")]
    public partial class CorreoAsaeCRM_AgendaEventoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int puerto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contra;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EmailCopia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string archivoNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string EventoTitulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.DateTime EventoFechaI;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.DateTime EventoFechaF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string EventoOrganizaNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string EventoOrganizaMail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string EventoAsunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string EventoDescripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string EventoUbicacion;
        
        public CorreoAsaeCRM_AgendaEventoRequestBody() {
        }
        
        public CorreoAsaeCRM_AgendaEventoRequestBody(
                    string host, 
                    int puerto, 
                    string usuario, 
                    string contra, 
                    string Email, 
                    string EmailCopia, 
                    string from, 
                    string Subject, 
                    string body, 
                    string archivoNombre, 
                    string EventoTitulo, 
                    System.DateTime EventoFechaI, 
                    System.DateTime EventoFechaF, 
                    string EventoOrganizaNombre, 
                    string EventoOrganizaMail, 
                    string EventoAsunto, 
                    string EventoDescripcion, 
                    string EventoUbicacion) {
            this.host = host;
            this.puerto = puerto;
            this.usuario = usuario;
            this.contra = contra;
            this.Email = Email;
            this.EmailCopia = EmailCopia;
            this.from = from;
            this.Subject = Subject;
            this.body = body;
            this.archivoNombre = archivoNombre;
            this.EventoTitulo = EventoTitulo;
            this.EventoFechaI = EventoFechaI;
            this.EventoFechaF = EventoFechaF;
            this.EventoOrganizaNombre = EventoOrganizaNombre;
            this.EventoOrganizaMail = EventoOrganizaMail;
            this.EventoAsunto = EventoAsunto;
            this.EventoDescripcion = EventoDescripcion;
            this.EventoUbicacion = EventoUbicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CorreoAsaeCRM_AgendaEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CorreoAsaeCRM_AgendaEventoResponse", Namespace="http://www.asae.com.mx", Order=0)]
        public CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoResponseBody Body;
        
        public CorreoAsaeCRM_AgendaEventoResponse() {
        }
        
        public CorreoAsaeCRM_AgendaEventoResponse(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.asae.com.mx")]
    public partial class CorreoAsaeCRM_AgendaEventoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorreoAsaeCRM_AgendaEventoResult;
        
        public CorreoAsaeCRM_AgendaEventoResponseBody() {
        }
        
        public CorreoAsaeCRM_AgendaEventoResponseBody(string CorreoAsaeCRM_AgendaEventoResult) {
            this.CorreoAsaeCRM_AgendaEventoResult = CorreoAsaeCRM_AgendaEventoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CorreoSoapChannel : CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorreoSoapClient : System.ServiceModel.ClientBase<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap>, CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap {
        
        public CorreoSoapClient() {
        }
        
        public CorreoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorreoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorreoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorreoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoResponse CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap.CorreoMetPrivado(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequest request) {
            return base.Channel.CorreoMetPrivado(request);
        }
        
        public string CorreoMetPrivado(string host, int puerto, string usuario, string contra, string Email, string from, string Subject, string body) {
            CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequest inValue = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequest();
            inValue.Body = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequestBody();
            inValue.Body.host = host;
            inValue.Body.puerto = puerto;
            inValue.Body.usuario = usuario;
            inValue.Body.contra = contra;
            inValue.Body.Email = Email;
            inValue.Body.from = from;
            inValue.Body.Subject = Subject;
            inValue.Body.body = body;
            CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoResponse retVal = ((CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap)(this)).CorreoMetPrivado(inValue);
            return retVal.Body.CorreoMetPrivadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoResponse> CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap.CorreoMetPrivadoAsync(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequest request) {
            return base.Channel.CorreoMetPrivadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoResponse> CorreoMetPrivadoAsync(string host, int puerto, string usuario, string contra, string Email, string from, string Subject, string body) {
            CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequest inValue = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequest();
            inValue.Body = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoMetPrivadoRequestBody();
            inValue.Body.host = host;
            inValue.Body.puerto = puerto;
            inValue.Body.usuario = usuario;
            inValue.Body.contra = contra;
            inValue.Body.Email = Email;
            inValue.Body.from = from;
            inValue.Body.Subject = Subject;
            inValue.Body.body = body;
            return ((CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap)(this)).CorreoMetPrivadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsResponse CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap.CorreoAsaeTickets(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequest request) {
            return base.Channel.CorreoAsaeTickets(request);
        }
        
        public string CorreoAsaeTickets(string host, int puerto, string usuario, string contra, string Email, string EmailCopia, string from, string Subject, string body) {
            CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequest inValue = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequest();
            inValue.Body = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequestBody();
            inValue.Body.host = host;
            inValue.Body.puerto = puerto;
            inValue.Body.usuario = usuario;
            inValue.Body.contra = contra;
            inValue.Body.Email = Email;
            inValue.Body.EmailCopia = EmailCopia;
            inValue.Body.from = from;
            inValue.Body.Subject = Subject;
            inValue.Body.body = body;
            CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsResponse retVal = ((CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap)(this)).CorreoAsaeTickets(inValue);
            return retVal.Body.CorreoAsaeTicketsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsResponse> CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap.CorreoAsaeTicketsAsync(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequest request) {
            return base.Channel.CorreoAsaeTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsResponse> CorreoAsaeTicketsAsync(string host, int puerto, string usuario, string contra, string Email, string EmailCopia, string from, string Subject, string body) {
            CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequest inValue = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequest();
            inValue.Body = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeTicketsRequestBody();
            inValue.Body.host = host;
            inValue.Body.puerto = puerto;
            inValue.Body.usuario = usuario;
            inValue.Body.contra = contra;
            inValue.Body.Email = Email;
            inValue.Body.EmailCopia = EmailCopia;
            inValue.Body.from = from;
            inValue.Body.Subject = Subject;
            inValue.Body.body = body;
            return ((CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap)(this)).CorreoAsaeTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoResponse CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap.CorreoAsaeCRM_AgendaEvento(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequest request) {
            return base.Channel.CorreoAsaeCRM_AgendaEvento(request);
        }
        
        public string CorreoAsaeCRM_AgendaEvento(
                    string host, 
                    int puerto, 
                    string usuario, 
                    string contra, 
                    string Email, 
                    string EmailCopia, 
                    string from, 
                    string Subject, 
                    string body, 
                    string archivoNombre, 
                    string EventoTitulo, 
                    System.DateTime EventoFechaI, 
                    System.DateTime EventoFechaF, 
                    string EventoOrganizaNombre, 
                    string EventoOrganizaMail, 
                    string EventoAsunto, 
                    string EventoDescripcion, 
                    string EventoUbicacion) {
            CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequest inValue = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequest();
            inValue.Body = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequestBody();
            inValue.Body.host = host;
            inValue.Body.puerto = puerto;
            inValue.Body.usuario = usuario;
            inValue.Body.contra = contra;
            inValue.Body.Email = Email;
            inValue.Body.EmailCopia = EmailCopia;
            inValue.Body.from = from;
            inValue.Body.Subject = Subject;
            inValue.Body.body = body;
            inValue.Body.archivoNombre = archivoNombre;
            inValue.Body.EventoTitulo = EventoTitulo;
            inValue.Body.EventoFechaI = EventoFechaI;
            inValue.Body.EventoFechaF = EventoFechaF;
            inValue.Body.EventoOrganizaNombre = EventoOrganizaNombre;
            inValue.Body.EventoOrganizaMail = EventoOrganizaMail;
            inValue.Body.EventoAsunto = EventoAsunto;
            inValue.Body.EventoDescripcion = EventoDescripcion;
            inValue.Body.EventoUbicacion = EventoUbicacion;
            CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoResponse retVal = ((CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap)(this)).CorreoAsaeCRM_AgendaEvento(inValue);
            return retVal.Body.CorreoAsaeCRM_AgendaEventoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoResponse> CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap.CorreoAsaeCRM_AgendaEventoAsync(CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequest request) {
            return base.Channel.CorreoAsaeCRM_AgendaEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoResponse> CorreoAsaeCRM_AgendaEventoAsync(
                    string host, 
                    int puerto, 
                    string usuario, 
                    string contra, 
                    string Email, 
                    string EmailCopia, 
                    string from, 
                    string Subject, 
                    string body, 
                    string archivoNombre, 
                    string EventoTitulo, 
                    System.DateTime EventoFechaI, 
                    System.DateTime EventoFechaF, 
                    string EventoOrganizaNombre, 
                    string EventoOrganizaMail, 
                    string EventoAsunto, 
                    string EventoDescripcion, 
                    string EventoUbicacion) {
            CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequest inValue = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequest();
            inValue.Body = new CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoAsaeCRM_AgendaEventoRequestBody();
            inValue.Body.host = host;
            inValue.Body.puerto = puerto;
            inValue.Body.usuario = usuario;
            inValue.Body.contra = contra;
            inValue.Body.Email = Email;
            inValue.Body.EmailCopia = EmailCopia;
            inValue.Body.from = from;
            inValue.Body.Subject = Subject;
            inValue.Body.body = body;
            inValue.Body.archivoNombre = archivoNombre;
            inValue.Body.EventoTitulo = EventoTitulo;
            inValue.Body.EventoFechaI = EventoFechaI;
            inValue.Body.EventoFechaF = EventoFechaF;
            inValue.Body.EventoOrganizaNombre = EventoOrganizaNombre;
            inValue.Body.EventoOrganizaMail = EventoOrganizaMail;
            inValue.Body.EventoAsunto = EventoAsunto;
            inValue.Body.EventoDescripcion = EventoDescripcion;
            inValue.Body.EventoUbicacion = EventoUbicacion;
            return ((CRM.EnvioCorreo.ReferenciaDeServicioDeCorreoDeASAE.CorreoSoap)(this)).CorreoAsaeCRM_AgendaEventoAsync(inValue);
        }
    }
}
